### ISSUE TITLE
index.d.ts is not bundled with pixi-tilemap 2.1.0

### ISSUE THREAD

**Issue by NintendoBen** [pixijs/pixi-tilemap#102]
It looks like the typescript definitions (index.d.ts) aren't included with the pixi-tilemap 2.1.0 bundle

![image](https://user-images.githubusercontent.com/639975/91640482-e8c48100-e9eb-11ea-911d-4a244da2bb84.png)

I tried to manually inject them just to test things out and there seems to be some sort of resolution issue with pixi.js (which could totally be my own configuration issue! Just not 100% sure...)

![image](https://user-images.githubusercontent.com/639975/91640559-7e601080-e9ec-11ea-8774-abb74d053063.png)

![image](https://user-images.githubusercontent.com/639975/91640593-ae0f1880-e9ec-11ea-825b-2966d18fc534.png)

**Comment by NintendoBen** [comment]
I think the problem I'm having is just the nature of TypeScript not working well with the existing pixi plugin architecture which benefits from JavaScript's flexibility. I'll probably just have to find a way to make TypeScript happy 😄

**Comment by NintendoBen** [comment]
As a temporary workaround, I created a copy of the pixi-tilemap.d.ts type definitions in my own source/types and retargeted the @pixi module imports to point at "pixi.js" instead and smoothed out a couple warnings here and there like changing "String" to "string", etc... So far things seem to be working ok!

**Comment by SukantPal** [comment]
@NintendoBen This will be fixed in the next release of pixi.js (pixijs/pixi.js). Each scoped @pixi/ package will ship with its own typings.

**Comment by SukantPal** [comment]
@NintendoBen Here's the PR btw: https://github.com/pixijs/pixi.js/pull/6849

**Comment by NintendoBen** [comment]
Thanks for the info @SukantPal ! 😁

That will definitely solve the pixi type definition issue(s), but I think that the pixi-tilemap definitions will still be missing until they get bundled within the pixi-tilemap npm package root? Unless I’m missing something - I don’t consider myself a TypeScript expert!

**Comment by SukantPal** [comment]
Wait, the index.d.ts file isn't in the shipped npm package?

**Comment by NintendoBen** [comment]
That’s right I believe 😅

**Comment by SukantPal** [comment]
https://github.com/pixijs/pixi-tilemap/blob/master/index.d.ts

How could that be? @ivanpopelyshev ^^

**Comment by SukantPal** [comment]
@NintendoBen Dod you figure out why the index.d.ts is missing?

**Comment by NintendoBen** [comment]
I’m not sure to be honest - just running npm install, it seems like the index.d.ts file doesn’t exist in the node_modules/pixi-tilemap folder. I’m not that familiar with the npm package publish process, so I’m not sure what could be going wrong.

**Comment by SukantPal** [comment]
@NintendoBen 2.1.3 was just released, can you try again?

**Comment by NintendoBen** [comment]
Will do - I’ll try it shortly 😊

**Comment by NintendoBen** [comment]
@SukantPal - looks like the index.d.ts file is included now! When I swap out my custom pixi-tilemap.d.ts definitions with the bundled pixi-tilemap/index.d.ts definitions, they're now picked up automatically by Visual Studio Code. The next trick will be to have the @pixi package typings generated and included 😄 

Thanks for responding so quickly to this 😁
