### ISSUE TITLE
Using a RenderTexture crash

### ISSUE THREAD

**Issue by starburst997** [pixijs/pixi-tilemap#12]
I wanted to use a RenderTexture instead and I was getting an error because the source of the base texture is "null".

Specifically it throw an error [here](https://github.com/pixijs/pixi-tilemap/blob/master/src/TileRenderer.ts#L7).

I was able to get around this with this small [modification](https://github.com/starburst997/pixi-tilemap/commit/b026f88d1c2272d0c55cbaa000d27502a5d98de4).

However this fix only works if you use a 2048x2048 RenderTexture. Also not quite sure why it works.

**Comment by ivanpopelyshev** [comment]
Current implementation packs 4 1024 textures into one of 2048, that was made for compatibility with rpgmaker. 

So your fix will work only if its using 1 texture. I wont merge it, but I'll take it into account :)
