### ISSUE TITLE
Remove a frame / tile ?

### ISSUE THREAD

**Issue by Oza94** [pixijs/pixi-tilemap#14]
Is it possible to remove a single frame or tile without clearing / populating all the `CompositeRectTileLayer` again ? I have a use case where player actions change the tilemap with small but frequent updates.

I've looked in the sources and did not find any method that seems to do that apart from `clear()`.

**Comment by ivanpopelyshev** [comment]
> I have a use case where player actions change the tilemap with small but frequent updates.

Don't worry, clear() and refill are fast. 
Two cases:

1. Every frame you clear and refill it - same as PIXI baseline performance
2. Nothing is changing - CPU usage is 0%

**Comment by Oza94** [comment]
Ok thanks I'll give it a try !

**Comment by SirJosh3917** [comment]
I was just curious, is allowing people to remove frames technically feasible? I've got a game where worlds can be big (not sure how big they will be in the final release but maybe under 1000x1000) and if I have to clear the map and iterate over all the blocks on multiple layers, that'd be really intensive. I suppose I could only redraw the tiles in view, but it'd be nice if there was a method to remove/replace old tiles. Would a method like that be technically feasible? Or would it be worse performant, or...? Just curious about the reasoning behind not offering something to do this from the get-go.

**Comment by ivanpopelyshev** [comment]
If you want to put million tiles in tilemap then there's something wrong on your high-level. 

You have to find my explanations about high-levels VS low-level here, in pixijs issues or here: https://www.html5gamedevs.com/search/?q=pixi-tilemap&quick=1&type=forums_topic
