### ISSUE TITLE
Rendering artifacts in the WebGL rpgmaker demos

### ISSUE THREAD

**Issue by danielytics** [pixijs/pixi-tilemap#16]
Hi, I was looking at the rpgmaker demos and noticed some artifacts. These do not occur in the canvas version:

On mobile safari on iOS, the tiles are not seemless. There's a very thin (it looks like 1 pixel) black line between tiles. Its not always there, but it flickers in and out as the demo scrolls (seems like a rounding error?). This happens in both the retina and normal demos.

On OSX (tested in both Safari and Chrome), the tiles ARE seamless, however the tiles on the edge of the screen don't draw (I can't tell if they only draw when fully visible, or if a certain amount of them is visible). This seems dependent on the speed of the scrolling, as when I manually pan around the map, it sometimes renders correctly and other times does not.
It seems that this happens consistently in the retina demos, and in the zoomin non-retina demo.

**Comment by ivanpopelyshev** [comment]
Updated. Try it again.

**Comment by danielytics** [comment]
Yes, both issues are now fixed - awesome! Thanks for the qucik fix 👍

However, there is one more: again, on safari on iOS, there is a vertical gap between some tiles. Its consistently the same tiles and only vertical lines (never horizontal).

![img_0144](https://user-images.githubusercontent.com/2631410/27649019-646ea5ce-5c28-11e7-9710-3b2eba113a1e.PNG)

**Comment by ivanpopelyshev** [comment]
OK, that's a bug that still hunts me. Clamping is wrong. However, if you use your own set of textures, and you have extra pixel at each side of tile that has the same color - it wont happen.

**Comment by danielytics** [comment]
It seems suspicious that its only that one water/grass boundary tile. There were others too, but I suspect its a limited set.

Is this a known bug? Feel free to close this issue. The original bugs are fixed now :) Thanks again!

**Comment by ivanpopelyshev** [comment]
That's because its position in tileset. It has some dark neighboring tiles at the right.

**Comment by danielytics** [comment]
Ahh, I see. Thanks for the explanation and quick fix. I'll close this issue.

**Comment by ivanpopelyshev** [comment]
Wait, lets try to fix it !

**Comment by ivanpopelyshev** [comment]
Did you clone and host it on your comp?

**Comment by ivanpopelyshev** [comment]
If so, try add 

```
PIXI.settings.PRECISION_FRAGMENT = PIXI.PRECISION.HIGH;
```

in the beginning of main.js

**Comment by danielytics** [comment]
No, I only ran your demos to see it in action before trying to use it myself. I will do so now though and test it with that change and report back.

**Comment by danielytics** [comment]
Actually, if you don't mind re-uploading, that will be faster for me to test on my iPad since I would need to serve up the HTML from somewhere and I don't have anywhere convenient setup right now.

**Comment by ivanpopelyshev** [comment]
Done, it will be updated soon (cache sucks!).

Btw, https://github.com/Alan01252/pixi-tilemap-tutorial is good tutorial.

**Comment by danielytics** [comment]
Yes, that does indeed seem to fix it for me!

Thanks for the link, I will read it shortly :)

**Comment by ivanpopelyshev** [comment]
Yes, it seems that "medium" precision on iphone has only 11 bits , while this tile appears at >1024 and cant be clamped to something like "1299.5", it clamps straight to 1300. I thought by standart it must be at least 12.

**Comment by danielytics** [comment]
Ahh, that's irritating. 11 bits is a very strange choice of precision.

**Comment by ivanpopelyshev** [comment]
May be my calculations aren't right, but we really have problems with it in pixi.js, people are complaining about shaking animations. HIGHP and another hack seem to solve it.
