### ISSUE TITLE
Should we add `break;` after this line ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-tilemap#19]
https://github.com/pixijs/pixi-tilemap/blob/7baa397a05a90aa66d3e7afc7e2b2b22060a045d/src/CompositeRectTileLayer.ts#L86

**Comment by ivanpopelyshev** [comment]
I dont think it matters

**Comment by finscn** [comment]
if no `break` , the texture will be added to every child.  Is it necessary ?

**Comment by ivanpopelyshev** [comment]
Ok, you're right.
