### ISSUE TITLE
[Bug] When textures.length >= 16 ,  can't render correctly.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-tilemap#21]
When I  create a CompositeRectTileLayer Object like this : 
```
tilemap = new PIXI.tilemap.CompositeRectTileLayer(0, tileTextures, true);
```
if tileTextures include `16` or `more than 16` textures , the map can't be rendered  correctly.
The result of rendering is like this : 
<img width="182" alt="2017-08-17 8 28 05" src="https://user-images.githubusercontent.com/288367/29390933-371bff06-82b9-11e7-8bd7-405254ce4d4a.png">

the 3 colors are not be included in any  tile texture. So strange.

**Comment by finscn** [comment]
I  found the key point of this bug : 
https://github.com/pixijs/pixi-tilemap/blob/master/src/TileRenderer.ts#L95

**Comment by ivanpopelyshev** [comment]
Agree.
