### ISSUE TITLE
I found I can't use `carmack scroll algorithm` in pixi-tilemap.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-tilemap#32]
We can't remove some frames of all frames after `addFrame` , 
We have to remove all , or keep all .

So  can't use `carmack scroll algorithm` in pixi-tilemap.

Is it ?

**Comment by ivanpopelyshev** [comment]
The idea of pixi-tilemap is to refill tilemap completely whenever the camera touches the edge of "filled" part of tilemap. Its easier than `carmack`. I think carmack is certainly better for `canvas2d` and RMMV uses it, but for webgl i think its the same.

**Comment by finscn** [comment]
I see & I agree with you.
