### ISSUE TITLE
[Bug] Don't support  `one tile covers another one`

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-tilemap#33]
When a tile has something (e.g.  grass )  need to  cover other tile.

They can't be rendering correct.

![image](https://user-images.githubusercontent.com/288367/30523862-ce97e80a-9bae-11e7-9cd7-6f471853f6fc.png)

![image](https://user-images.githubusercontent.com/288367/30523876-ffcd60d0-9bae-11e7-9a0c-0813a41642dd.png)

**Comment by ivanpopelyshev** [comment]
Isn't that problem of how do you order tiles?

**Comment by finscn** [comment]
I think I'm right . I debug & test . the order is right.
 I've used Tiled many years , and  wrote some Tiled's lib/tools/utils  with different game engines.
I think  I don't   make the basic mistake.

of course , maybe I maked some other mistakes.
But I've no idea now. So sad.

Could you give me some adviace ?

BTW , When I render the map with PIXI.ParticleContainer &  many Sprites, everything  is OK.

The logics of these tow ways  are the same .

.

**Comment by ivanpopelyshev** [comment]
Well take only 5x5 map and look the order you call addRect().

**Comment by finscn** [comment]
<img width="484" alt="2017-09-18 3 26 26" src="https://user-images.githubusercontent.com/288367/30524171-3cc00b50-9bb4-11e7-8521-14019e923202.png">

I make a 1*2 , the order is right 
index 23 is water , 7 is grass .

x y is a relative postion.

**Comment by finscn** [comment]
I found that : 
the tile with big index is be put into  the last  child (children) of CompositeRectTileLayer.
```
                var layers = this.children;
                for (var i = 0; i < layers.length; i++)
                    layers[i].renderWebGL(renderer, this.useSquare);
```
So , the rendering order is not as same as  addFrame/addRect order.

**Comment by ivanpopelyshev** [comment]
Then make it that way it belongs only to one layer.

**Comment by finscn** [comment]
one layer only could include 16 textures.
one texture is one tile . the tileset include many tiles.

**Comment by ivanpopelyshev** [comment]
then how does it work with ParticleContainer?

**Comment by finscn** [comment]
Because this code 
 ```
               var maxTextures = this.maxTextures;
                if (len > 4 * maxTextures) {
                    return;
                }
```
the texPerChild could not bigger than 16.

**Comment by finscn** [comment]
I create many sprites as tiles.
It's stupid.
because the pixi don't support the feature like this : 
```
sprite.position.set( 10,10);
render.render(sprite);
sprite.position.set( 50,50);
render.render(sprite);
````
even though  , the tiles are the same , I have to create a new sprite.

**Comment by finscn** [comment]
I love this feature I suggested , but no one  like it https://github.com/pixijs/pixi.js/issues/3388

**Comment by finscn** [comment]
Current maxTextures = 4.
I don't what's mean , but I see this 
 http://webglstats.com/webgl/parameter/MAX_TEXTURE_IMAGE_UNITS 
most devices support 16 textures .  so may be we could change the maxTextures to 8 or 16.
Then texPerChild could be 4*8 or 4*16. I think it's enough

**Comment by ivanpopelyshev** [comment]
May be you mistake Texture for BaseTexture?

**Comment by finscn** [comment]
"May be you mistake Texture for BaseTexture?"  what's mean ?

**Comment by finscn** [comment]
```
    // `imgLoader` is a function that load img object by `tileset.name , tileset.image`
    Map.prototype.createTileTextures = function(imgLoader) {
        var baseTextureTable = {};

        for (var i = 0, len = this.tilesetList.length; i < len; i++) {
            var tileset = this.tilesetList[i];
            var name = tileset.name;
            var image = tileset.image;
            var baseTexture;
            if (typeof imgLoader === 'function') {
                baseTexture = PIXI.BaseTexture.from(imgLoader(name, image));
            } else {
                baseTexture = PIXI.BaseTexture.from(image);
            }
            baseTextureTable[name] = baseTexture;
        }

        var tileTextures = [];

        for (var i = 0, len = this.tileList.length; i < len; i++) {
            var t = this.tileList[i];
            var baseTexture = baseTextureTable[t.tileset];
            var texture = new PIXI.Texture(baseTexture,
                new PIXI.Rectangle(t.x, t.y, t.w, t.h)
            );
            tileTextures.push(texture);
        }

        return tileTextures;
    };

    Map.prototype.createTilemap = function(tileTextures, texPerChild) {
        var tilemap = new PIXI.tilemap.CompositeRectTileLayer(0, tileTextures, false, texPerChild);

        return tilemap;
    };
```

Is there something wrong ?

Thanks

**Comment by ivanpopelyshev** [comment]
Ok, how many images do you have there? Can you assemble them into an atlas?

**Comment by finscn** [comment]
@ivanpopelyshev  , the image file (tileset) just one png.

**Comment by finscn** [comment]
@ivanpopelyshev ,  I think maybe pixi-tilemap needs a deep refactor.

* support big tileset image
* support more textures
* The order of rendering should be as same as  the order of calling `addFrame`.

**Comment by ivanpopelyshev** [comment]
agree

**Comment by finscn** [comment]
Do you have some new plan or roadmap about pixi-tilemap ?
