### ISSUE TITLE
[QUESTION] Catch tile event

### ISSUE THREAD

**Issue by romontei** [pixijs/pixi-tilemap#58]
Hi ! Does anyone have a solution for catching tile events? I did not find anything that allows me to catch a click on a tile for example. Thx !

**Comment by ivanpopelyshev** [comment]
pixi-tilemap doesn't support it. However if you know how pixi handles interaction, it wont be difficult to add a `containsPoint` function in your tilemap and make it interactable. That function should iterate over all layers over all tiles and check which one is under the mouse. If you need extra fields in tile buffer for that - add them, modify the library to add something like "tileNumber" as an argument.

**Comment by roitto** [comment]
I'm pretty sure someone else will find this issue from Google.

_"How do i make pixi-tilemap tiles clickable?"_

I followed Ivans instructions about how pixi handles interactions and searched the Pixi source code for a bit. _(Which seems to be a good way to get better at using Pixi, i learned a ton of new stuff. :) )_

Then I was able to create interaction support to my tilemap. To make someone elses day a little better, i'm going to share my results.

Heres my code:
```javascript
        const tempPoint = new PIXI.Point();
        const tilemap = new PIXI.tilemap.CompositeRectTileLayer(0, this.tilemap);

        tilemap.containsPoint = (position) => {
            // Turns the mouse screen coordinate to the renderers coordinate.
            tilemap.worldTransform.applyInverse(position, tempPoint);

            // I'm only using the buffer from the first children/layer. Loop the whole layer if needed.
            const buffer = tilemap.children[0].pointsBuf;

            // Each tile data length in the buffer is 10, so slicing the array using 10 loops trough every tile from the buffer.
            // Is there any faster/more optimized way to do this? 
            for (let i = 0, let len = buffer.length; i < len; i+=10) {
                const data = buffer.slice(i, i + 10);

                // data[2] is the x coordinate in the buffer.
                // data[3] is the y coordinate in the buffer.
                // 16 is the width/height of the tile. You could also get the tile width/height from the buffer if you want to.
                // The calculation rounds to next lowest number that is dividable by 16 for the given coordinate.
                if (data[2] === Math.floor(tempPoint.x/16) * 16 && data[3] === Math.floor(tempPoint.y/16) * 16) {
                    return true;
                }
            }
            return false;
        };

        tilemap.interactive = true;

        tilemap.on('pointerdown', () => {
            console.log('You clicked a pixi-tilemap tile!');
        });
```

The given code does not get any information about the tile itself, it only makes the tile "interactive." But this gives a good enough template to further process the code for more features.
E.g you could get the tile data from somewhere using the tiles coordinates, or as Ivan said, you could store optional variables to the buffer if you modify the pixi-tilemap source a bit.

**Comment by Thijmen** [comment]
@roitto Old issue, but I'm struggling with it atm.

Why would one apply a tempPoint? That point's X and Y changes on every reload for me. For instance, I have a width of 34 and a height of 17. I never get to the point where I can make it actually clickable.
