### ISSUE TITLE
Is there any limit on addFrame count?

### ISSUE THREAD

**Issue by rkdrnf** [pixijs/pixi-tilemap#60]
I'm rendering map of 400 x 400 grid with size of each grid 16 x 16 pixels.
each grid shares single base texture.
each time player moves, I call addFrame for each grid of area around player.
But after certain point, around 18000 call maybe, addFrame does render nothing.

Is there any limits I'm missing?

**Comment by ivanpopelyshev** [comment]
Yeah, index buffer is 16-bit so its up to 65536 vertices, that means only 16384 tiles because tile is 4 vertices.

The idea is to refill whole tilemap regularly, for example, if you maintain a window size of 2 screens, and camera hits it.

**Comment by rkdrnf** [comment]
Thank you! I will try that 👍
