### ISSUE TITLE
Glitches with boundCountPerBuffer: 1

### ISSUE THREAD

**Issue by borisblizzard** [pixijs/pixi-tilemap#78]
When using boundCountPerBuffer: 1 (using maxTextures: 1 can help the reproduction be 100%) and the tilemap textures aren't the same size, glitches start to occur. I was able to track down the issue and fix it by adding this line at the end of TileRenderer.bindTexturesWithoutRT:

`renderer.shader.bind(shader, false);`

The issue seems to be related to how CompositeTileRectLayer renders TileRectLayer instances, but doesn't compensate for changed uSamplerSize between the textures used in the different TileRectLayer children.

Can this issue be confirmed and the fix (or an alternate, better fix) be integrated into the codebase?

**Comment by ivanpopelyshev** [comment]
First time I hear that. Yes, please reproduce it and I'll fix it.

**Comment by ivanpopelyshev** [comment]
Oh, wait, you already have a fix. Yes, I understand what the problem is, i'll apply your fix soon :)

**Comment by ivanpopelyshev** [comment]
OK, can you check the version in this repo in `dist` folder? if it works for you, I'll publish it in npm as 2.0.6

**Comment by borisblizzard** [comment]
Yup, your variant of the fix works as well.

**Comment by borisblizzard** [comment]
Actually wait, it seems that your variant doesn't seem to work in all cases for some reason. Not sure why.

**Comment by ivanpopelyshev** [comment]
OK, published.

**Comment by ivanpopelyshev** [comment]
I moved that line after all uniforms are set. Its a thing for v5 - need to bind shader to update them.

https://github.com/pixijs/pixi-tilemap/commit/9c8229b646b408d4dd51414dbc340edd8511e614#diff-a7f7a167801670fe73489ec251aad5b7L176-R189
