### ISSUE TITLE
Flipping tiles on an axis?

### ISSUE THREAD

**Issue by jessebraham** [pixijs/pixi-tilemap#83]
[Tiled](https://www.mapeditor.org/) allows you to flip tiles along either or both of the `x` and `y` axes. Parsing the map file and identifying flipped tiles was trivial, however I'm not seeing any method of rendering the tile on a `CompositeRectTileLayer` with the transform(s) applied. Is there currently any way to accomplish this?

**Comment by ivanpopelyshev** [comment]
It works both in v4 and v5: https://github.com/pixijs/pixi-tilemap/blob/master/demo/basic.js#L74

https://pixijs.io/examples/#/textures/texture-rotate.js

**Comment by jessebraham** [comment]
Gotcha, thanks. I had my mind set on "flip" and didn't think to read "rotate".

**Comment by ivanpopelyshev** [comment]
Yes, I just have enough math knowledge to realize its the same thing basically :) Strange that it doesnt exist in other renderers.
