### ISSUE TITLE
Screen Clipping Off?

### ISSUE THREAD

**Issue by steppers** [pixijs/pixi-tilemap#9]
Hi, I'm using this for some university coursework. I really don't like how the tiles don't render when they are > 50% offscreen. I can't find where this is being done so is there a way to change this to only cull when a tile is 100% offscreen?

Thanks,
Steppers

**Comment by ivanpopelyshev** [comment]
Hi! How do you fill the tilemap? In which browser did you see the clipping?

**Comment by steppers** [comment]
Chrome. The tiles closest the edge of the window get culled when they are half out :(

**Comment by ivanpopelyshev** [comment]
1. Try pass "false" as third parameter (use rects instead of squares)

```
var tilemap = new PIXI.tilemap.CompositeRectTileLayer(0, [resources['atlas_image'].texture], false); //<--here
```

2. Try https://github.com/pixijs/pixi-tilemap/tree/dev-multitexture , its experimental branch, I changed a lot in it. Allows up to 12 textures of 1024x1024 size

**Comment by steppers** [comment]
The first one worked. 
Thanks, a ton! :)
