### ISSUE TITLE
Request - support for compiling as an UMD module + support for pixijs-legacy

### ISSUE THREAD

**Issue by blurymind** [pixijs/pixi-tilemap#92]
Hi everyone, basically I am on a quest to get pixi-tilemap to become a first class object inside gdevelop, but after we migrated to Pixi5, a new technical hurdle has been encountered.
Gdevelop now requires from the library the ability to function as a UMD module. 
https://github.com/4ian/GDevelop/issues/503#issuecomment-667599003

What does that mean?
https://riptutorial.com/javascript/example/16339/universal-module-definition--umd-#example

 To quote @4ian , for our use case it basically means

> The idea is to surround the whole exported code inside a function. This function is taking PIXI as an argument and returning the Pixi Tilemap object. This functions does three things:
> 
> it checks if you're inside a "Node.js like" environment (also called the "CommonJS" way), and if yes, it requires pixi.js (well, pixi.js-legacy for us), pass it to the function, then assign the return result (Pixi Tilemap object) to module.exports.
> it checks if you're inside a "AMD environment" (also called the "require.js" way). In GDevelop, we're never using this so you can forget about this.
> otherwise, it assumes you're in a browser so it passes PIXI global object, and assign the return result (Pixi Tilemap object) to PIXI.tilemap (I guess).
> The 1. is used by the IDE, and 3. is used at Runtime.

The thing is I am not a fan of forking libraries and would much rather use the official release. This is why I decided to open an issue here and see if compiling to pixi-tilemap.umd.js is welcome here as a pr.

From what I see the dist files are created using tsconfig.json, but I have no idea how to set it up to generate what we want here.
Some help would be greatly appreciated :)

**Comment by ivanpopelyshev** [comment]
So many times I told for all my pluigins: make a PR, I'll accept it. 
Make sure it generates correct TS definitions both for vanilla. 

AMD/UMD i honestly dont care, im a mathematician, I use whatever other people make for me.

**Comment by blurymind** [comment]
I will look into it

**Comment by blurymind** [comment]
submitted a PR now - currently testing it inside gdevelop

**Comment by blurymind** [comment]
closing this issue now since a umd build has been merged
